export const PRISMA = {
  ERRORS: {
    UNIQUE_CONSTRAINT: 'P2002',
    DB_CONSTRAINT: 'P2004',
    FOREIGN_KEY_CONSTRAINT: 'P2003',
    DEPENDENCY_ON_OTHER_FIELDS: 'P2025',
    REQUIRED_RECORDS_NOTFOUND: 'P2025',
  },
};
